alter session set "_oracle_script" = true;

CREATE OR REPLACE VIEW ADMIN.UV_NHANVIEN_NHANVIEN AS
    SELECT *
    FROM ADMIN.NHANVIEN
    WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');
/
CREATE OR REPLACE VIEW ADMIN.UV_NHANVIEN_PHANCONG AS
    SELECT *
    FROM ADMIN.PHANCONG
    WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');
/

drop role NHANVIEN_ROLE;
create role NHANVIEN_ROLE;

grant SELECT ON ADMIN.UV_NHANVIEN_NHANVIEN TO NHANVIEN_ROLE;
grant UPDATE (NGAYSINH, DIACHI, SODT) ON ADMIN.UV_NHANVIEN_NHANVIEN TO NHANVIEN_ROLE;
grant SELECT ON ADMIN.UV_NHANVIEN_PHANCONG TO NHANVIEN_ROLE;
grant SELECT ON ADMIN.PHONGBAN TO NHANVIEN_ROLE;
grant SELECT ON ADMIN.DEAN TO NHANVIEN_ROLE;

drop user NV002;
create user NV002 identified by NV002;
grant create session to NV002;
grant NHANVIEN_ROLE to NV002;