alter session set "_ORACLE_SCRIPT" = true;

DROP ROLE QUANLY_ROLE;
CREATE ROLE QUANLY_ROLE;
/
GRANT NHANVIEN_ROLE TO QUANLY_ROLE;
/
CREATE OR REPLACE VIEW ADMIN.UV_QUANLY_NHANVIEN AS
    SELECT MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, VAITRO, MANQL, PHG 
    FROM ADMIN.NHANVIEN
    WHERE MANQL = SYS_CONTEXT('USERENV', 'SESSION_USER');
/
CREATE OR REPLACE VIEW ADMIN.UV_QUANLY_PHANCONG AS
    SELECT PC.MANV, PC.MADA, PC.THOIGIAN
    FROM ADMIN.PHANCONG PC, ADMIN.NHANVIEN NV
    WHERE MANQL = SYS_CONTEXT('USERENV', 'SESSION_USER') AND NV.MANV = PC.MANV;
/
GRANT SELECT ON ADMIN.UV_QUANLY_NHANVIEN TO QUANLY_ROLE;
GRANT SELECT ON ADMIN.UV_QUANLY_PHANCONG TO QUANLY_ROLE;
/
GRANT QUANLY_ROLE TO NV001;

