alter session set "_ORACLE_SCRIPT" = true;

DROP ROLE TRPHG_ROLE;
CREATE ROLE TRPHG_ROLE;
/
GRANT NHANVIEN_ROLE TO TRPHG_ROLE;
/
CREATE OR REPLACE VIEW ADMIN.UV_TRPHG_NHANVIEN AS
    SELECT MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, VAITRO, MANQL, PHG 
    FROM ADMIN.NHANVIEN NV, ADMIN.PHONGBAN PB
    WHERE TRPHG = SYS_CONTEXT('USERENV', 'SESSION_USER') AND NV.PHG = PB.MAPB;
/
GRANT SELECT ON ADMIN.UV_TRPHG_NHANVIEN TO TRPHG_ROLE;
/
drop user NV004;
create user NV004 identified by NV004;
grant create session to NV004;
/
GRANT TRPHG_ROLE TO NV004;

