create role NHANSU_ROLE;
GRANT NHANVIEN_ROLE TO NHANSU_ROLE;
GRANT EXECUTE ON ADMIN.InsertNV to NHANVIEN_ROLE;
GRANT UPDATE(MANV,TENNV,PHAI,NGAYSINH,DIACHI,SODT,VAITRO,MANQL,PHG) ON ADMIN.NHANVIEN TO NHANSU_ROLE;

GRANT SELECT ON ADMIN.UV_NHANSU_NHANVIEN TO NHANSU_ROLE;
GRANT INSERT, UPDATE ON ADMIN.PHONGBAN TO NHANSU_ROLE;

CREATE OR REPLACE VIEW ADMIN.UV_NHANSU_NHANVIEN AS
    SELECT MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, VAITRO, MANQL, PHG 
    FROM ADMIN.NHANVIEN;

CREATE OR REPLACE PROCEDURE ADMIN.InsertNV (
    MANV IN VARCHAR,
    TENNV IN NVARCHAR2,
    PHAI IN NVARCHAR2,
    NGAYSINH IN DATE,
    DIACHI IN NVARCHAR2,
    SODT IN VARCHAR,
    VAITRO IN NVARCHAR2,
    MANQL IN VARCHAR,
    PHG IN VARCHAR
)
AS
BEGIN
    DECLARE
        nv_count NUMBER;
        nmanv varchar2(5);
    BEGIN
        nmanv:=MANV;
        SELECT COUNT(*) INTO nv_count FROM ADMIN.NHANVIEN nv WHERE nv.MANV = nmanv;

        IF nv_count > 0 THEN
            RAISE_APPLICATION_ERROR (-20001, 'Da ton tai nhan vien');
        ELSE
            EXECUTE IMMEDIATE 'INSERT INTO ADMIN.NHANVIEN VALUES (:1, :2, :3, :4, :5, :6, NULL, NULL, :7, :8, :9)'
                USING MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, VAITRO, MANQL, PHG;
        END IF;
    END;
END;

begin
 ADMIN.InsertNV('NV006', 'Nguyen Van Chu', 'Nam', to_date('1992-03-07', 'YYYY-MM-DD'), 'Quan 2', '0768897093', 'Nhan vien', 'QL001', 'PB002');
end;
/
create user NS003 identified by NS003;
grant create session to NS003;
grant NHANSU_ROLE to NS003;